// built in imports
import { Heart, ShoppingCart } from "lucide-react";

// custom imports

// navbar links
export const NavbarLinks = [
  { name: "Categories", link: "/filter" },
  { name: "Deals", link: "/dealPage" },
  { name: "Sellers", link: "/sellerPage" },
  { name: "New Arrivals", link: "/newArivalsPage" },
];

// navbar navigation buttons
export const NavbarButtons = [
  { link: "/wishListPage", icon: Heart },
  { link: "/shop", icon: ShoppingCart },
];

// temp product data
export const Products = [
  {
    id: 1,
    brand: "TechGear Pro",
    name: "Quantum Watch X",
    price: 129,
    originalPrice: 215,
    discount: 40,
    image:
      "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop",
  },
  {
    id: 2,
    brand: "AudioPure",
    name: "Sonic Wave Pro",
    price: 299,
    originalPrice: 399,
    discount: 25,
    image:
      "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop",
  },
  {
    id: 3,
    brand: "LuxeKitchen",
    name: "Aura Brew Maker",
    price: 450,
    originalPrice: 530,
    discount: 15,
    image:
      "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=300&fit=crop",
  },
  {
    id: 4,
    brand: "EcoStride",
    name: "Vapor Flow V2",
    price: 85,
    originalPrice: 170,
    discount: 50,
    image:
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
  },
  {
    id: 5,
    brand: "SoundCore",
    name: "Bass Pro X1",
    price: 199,
    originalPrice: 280,
    discount: 30,
    image:
      "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=300&fit=crop",
  },
  {
    id: 6,
    brand: "FitTech",
    name: "Band Ultra 5",
    price: 59,
    originalPrice: 99,
    discount: 40,
    image:
      "https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?w=400&h=300&fit=crop",
  },
];

// temp verified seller
export const Sellers = [
  {
    id: 1,
    name: "TechGear Pro",
    category: "Premium Electronics",
    followers: "12k+",
    rating: "4.9/5",
    logo: "https://placehold.co/80x80/e0e7ff/4f46e5?text=TG&font=montserrat",
    logoBg: "bg-indigo-50",
  },
  {
    id: 2,
    name: "Luxe Living",
    category: "Lifestyle & Decor",
    followers: "45k+",
    rating: "4.8/5",
    logo: "https://placehold.co/80x80/fef9ee/d97706?text=LL&font=montserrat",
    logoBg: "bg-amber-50",
  },
  {
    id: 3,
    name: "BioGlow",
    category: "Organic Beauty",
    followers: "8k+",
    rating: "5.0/5",
    logo: "https://placehold.co/80x80/f0fdf4/16a34a?text=BG&font=montserrat",
    logoBg: "bg-green-50",
  },
  {
    id: 4,
    name: "NeoTrend",
    category: "Contemporary Fashion",
    followers: "22k+",
    rating: "4.7/5",
    logo: "https://placehold.co/80x80/fdf2f8/9333ea?text=NT&font=montserrat",
    logoBg: "bg-purple-50",
  },
];

// Product Data For Filter Page
export const ProductDataForFilterPage = [
  {
    id: 1,
    title: "Acoustix Elite Wireless Headphones Gen 4",
    brand: "Sonic Pro Audio",
    isBrandVerified: false,
    rating: 4.9,
    badge1: "-25% OFF",
    badge2: "TOP RATED",
    originalPrice: 499.0,
    currentPrice: 374.25,
  },
  {
    id: 2,
    title: 'PulseVision Ultra 4K Smart Monitor 27"',
    brand: "QuantumDisplay",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-15% OFF",
    badge2: "BESTSELLER",
    originalPrice: 649.0,
    currentPrice: 551.65,
  },
  {
    id: 3,
    title: "ChromaMech RGB Wireless Mechanical Keyboard",
    brand: "HyperKey Studio",
    isBrandVerified: true,
    rating: 4.7,
    badge1: "-30% OFF",
    badge2: "NEW ARRIVAL",
    originalPrice: 179.99,
    currentPrice: 125.99,
  },
  {
    id: 4,
    title: "Lumina Ultra Light ANC Earbuds Pro",
    brand: "Sonic Pro Audio",
    isBrandVerified: true,
    rating: 4.9,
    badge1: "-20% OFF",
    badge2: "TOP RATED",
    originalPrice: 229.0,
    currentPrice: 183.2,
  },
  {
    id: 5,
    title: "ApexTracker Pro Multisport GPS Watch",
    brand: "ChronoFit",
    isBrandVerified: true,
    rating: 4.6,
    badge1: "-40% OFF",
    badge2: "LIMITED STOCK",
    originalPrice: 399.0,
    currentPrice: 239.4,
  },
  {
    id: 6,
    title: "Zenith Lens 35mm F/1.4 Mirrorless Prime",
    brand: "Optix Optics",
    isBrandVerified: true,
    rating: 4.9,
    badge1: "-10% OFF",
    badge2: "EDITOR'S CHOICE",
    originalPrice: 899.0,
    currentPrice: 809.1,
  },
  {
    id: 7,
    title: "AeroGlide Ergonomic Wireless Mouse X",
    brand: "TechMotion",
    isBrandVerified: true,
    rating: 4.5,
    badge1: "-35% OFF",
    badge2: "HOT DEAL",
    originalPrice: 89.99,
    currentPrice: 58.49,
  },
  {
    id: 8,
    title: "Atmosphere Smart Studio Condenser Mic",
    brand: "VocalCraft",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-25% OFF",
    badge2: "TOP RATED",
    originalPrice: 249.0,
    currentPrice: 186.75,
  },
  {
    id: 9,
    title: 'NeoSlate Pro 12.9" Digital Drawing Tablet',
    brand: "ArtistryTech",
    isBrandVerified: true,
    rating: 4.7,
    badge1: "-18% OFF",
    badge2: "TRENDING",
    originalPrice: 799.0,
    currentPrice: 655.18,
  },
  {
    id: 10,
    title: "Velocity G7 High-Speed NVMe SSD 2TB",
    brand: "NovaStorage",
    isBrandVerified: true,
    rating: 4.9,
    badge1: "-50% OFF",
    badge2: "FLASH SALE",
    originalPrice: 259.99,
    currentPrice: 129.99,
  },
  {
    id: 11,
    title: "CinemaSound 5.1 Dolby Atmos Soundbar",
    brand: "Sonic Pro Audio",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-30% OFF",
    badge2: "BESTSELLER",
    originalPrice: 599.0,
    currentPrice: 419.3,
  },
  {
    id: 12,
    title: "OmniSphere 360 Waterproof Action Camera 8K",
    brand: "Horizon Cam",
    isBrandVerified: true,
    rating: 4.6,
    badge1: "-15% OFF",
    badge2: "TOP RATED",
    originalPrice: 449.0,
    currentPrice: 381.65,
  },
  {
    id: 13,
    title: "TitanPad XL Desk Mat & Wireless Charger",
    brand: "HyperKey Studio",
    isBrandVerified: true,
    rating: 4.7,
    badge1: "-20% OFF",
    badge2: "NEW ARRIVAL",
    originalPrice: 69.99,
    currentPrice: 55.99,
  },
  {
    id: 14,
    title: "StealthStream Wireless VR Headset Gen 2",
    brand: "Nexus Reality",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-25% OFF",
    badge2: "TOP RATED",
    originalPrice: 699.0,
    currentPrice: 524.25,
  },
  {
    id: 15,
    title: "PowerBank Pro 30,000mAh 100W Fast Charge",
    brand: "VoltGrid",
    isBrandVerified: true,
    rating: 4.9,
    badge1: "-40% OFF",
    badge2: "BESTSELLER",
    originalPrice: 119.99,
    currentPrice: 71.99,
  },
  {
    id: 16,
    title: "SmartBrew Precision Thermal Coffee Maker",
    brand: "Artisan Home",
    isBrandVerified: true,
    rating: 4.7,
    badge1: "-10% OFF",
    badge2: "FEATURED",
    originalPrice: 199.0,
    currentPrice: 179.1,
  },
  {
    id: 17,
    title: "AirFlow Pro HEPA Smart Air Purifier",
    brand: "PureBreathe",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-35% OFF",
    badge2: "TOP RATED",
    originalPrice: 289.0,
    currentPrice: 187.85,
  },
  {
    id: 18,
    title: "GameStation Pro Wireless Haptic Controller",
    brand: "PixelPlay",
    isBrandVerified: true,
    rating: 4.6,
    badge1: "-22% OFF",
    badge2: "HOT DEAL",
    originalPrice: 79.99,
    currentPrice: 62.39,
  },
  {
    id: 19,
    title: "StudioPulse Active Noise Cancelling Earbuds",
    brand: "Sonic Pro Audio",
    isBrandVerified: true,
    rating: 4.7,
    badge1: "-30% OFF",
    badge2: "BESTSELLER",
    originalPrice: 159.0,
    currentPrice: 111.3,
  },
  {
    id: 20,
    title: "OrbitDock USB-C Dual 4K Thunderbolt Hub",
    brand: "TechMotion",
    isBrandVerified: true,
    rating: 4.8,
    badge1: "-15% OFF",
    badge2: "NEW ARRIVAL",
    originalPrice: 189.99,
    currentPrice: 161.49,
  },
];

// footer links
export const footerLinks = {
  Company: [
    { title: "About Kinetic", link: "/company?section=about-kinetic" },
    { title: "Sustainability", link: "/company?section=sustainability" },
    { title: "Careers", link: "/company?section=careers" },
    { title: "Press Kit", link: "/company?section=press-kit" },
  ],
  Support: [
    { title: "Customer Support", link: "/support" },
    {
      title: "Seller Center",
      link: "http://localhost:5174/",
      isExternal: true,
    },
    { title: "Shipping Info", link: "/shipping-info" },
    { title: "Affiliate Program", link: "/affiliate-program" },
  ],
  Legal: [
    { title: "Terms of Service", link: "/terms-of-service" },
    { title: "Privacy Policy", link: "/privacy-policy" },
    { title: "Cookies Policy", link: "/cookies-policy" },
  ],
};

// companyContent static data
export const companyContent = [
  {
    id: 1,
    slug: "about-kinetic",
    title: "About Kinetic",
    content: [
      "Kinetic Market is a modern e-commerce platform built to make online shopping simple, reliable, and convenient. We bring a wide range of quality products together in one place, making it easier for customers to discover and purchase the products they need.",
      "Our focus is on providing a smooth shopping experience, from browsing products to receiving orders. We aim to offer clear product information, reliable service, secure payments, and dependable delivery.",
      "At Kinetic Market, we believe that good e-commerce is not just about selling products — it's about building trust with customers and continuously improving their shopping experience.",
    ],
    mission: {
      title: "Our Mission",
      content:
        "Our mission is to create a convenient and trustworthy online marketplace where customers can shop with confidence and sellers can grow their businesses.",
    },
  },
  {
    id: 2,
    slug: "sustainability",
    title: "Sustainability",
    content: [
      "At Kinetic Market, we believe that responsible business practices can help create a better future. We continuously look for ways to reduce unnecessary waste and make our operations more responsible.",
      "We focus on thoughtful packaging, efficient operations, and responsible business practices wherever possible. Our goal is to minimize our environmental impact while continuing to provide a reliable shopping experience for our customers.",
      "We are committed to improving our practices over time and supporting a more sustainable approach to e-commerce.",
    ],
  },
  {
    id: 3,
    slug: "careers",
    title: "Careers",
    content: [
      "At Kinetic Market, we believe that great products are built by talented and motivated people. We value creativity, teamwork, continuous learning, and a willingness to take on new challenges.",
      "We aim to create a positive and supportive work environment where people can improve their skills, share ideas, and contribute to meaningful projects.",
      "As Kinetic Market grows, we look forward to building a team of passionate people who want to learn, grow, and help shape the future of our platform.",
    ],
  },
  {
    id: 4,
    slug: "press-kit",
    title: "Press Kit",
    content: [
      "Kinetic Market is a modern e-commerce platform focused on providing customers with a simple, reliable, and convenient online shopping experience.",
      "Our platform brings quality products together in one place while focusing on customer trust, reliable service, and continuous improvement.",
      "This section provides general company and brand information for media, partners, and other interested parties.",
    ],
  },
];
